config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entitiy
    end
  end

  def show
    @lists = List.all
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-3">
  <h1>Bookmarks New</h1>
  <hr>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%# <%= f.association :movie, collection: Movie.all.map { |m| [m.title, m.id] } %>
      <%= f.association :movie, collection: Movie.all.order(:title) %>
      <%= f.input :comment %>
      <%= f.submit "Create List" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container mt-3" data-controller="changecolor">
  <h1 data-changecolor-target="title" data-action="click->changecolor#change">All Lists</h1>
  <%= link_to "Add List", new_list_path %>
  <hr>

  <% @lists.each do |list| %>
    <p><%= link_to list.name, list_path(list) %></p>
    <br>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container mt-3">
  <h1>Lists New</h1>
  <hr>

  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.submit "Create List" %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
  <%= link_to "Home", root_path %>
  <%= link_to "Add To List", new_list_bookmark_path(@list) %>
  <hr>
  <% @list.movies.each do |movie| %>
   <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
    <div class="container">
      <h3><%= movie.title %></h3>
      <p><%= movie.overview %></p>
      <img src="<%= movie.poster_url%>" alt="<%= movie.title %>" style="width:200px">
      <p><%= bookmark.comment %></p>
    </div>
    <br>
  <% end %>
</div>